version: '3.8'

services:
  phpfpm:
    build:
      context: .
      dockerfile: ./docker/phpfpm/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./docker/phpfpm/php.ini:/usr/local/etc/php/php.ini
    ports:
      - '9000:9000'

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf
      - ./src:/src
    ports:
      - '80:80'
    depends_on:
      - phpfpm
      - db

  db:
    image: mysql:8.0.22
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DB=dbname
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - '5432:5432'

  redis:
    image: redis:6.0.7
    volumes:
      - ./redis:/data
    restart: always

volumes:
  db_data:

